### ISSUE TITLE
Unable to lock project!

### ISSUE THREAD

**Issue by TridentFactor** [Cisco-Talos/Ghidraaas#1]
ERROR Abort due to Headless analyzer error: Unable to lock project! /opt/ghidra_projects/252ad75af5ba26cf432c10164635da0d3402e6963853052ea6a76d42180e7b69 (HeadlessAnalyzer) java.io.IOException: Unable to lock project! /opt/ghidra_projects/252ad75af5ba26cf432c10164635da0d3402e6963853052ea6a76d42180e7b69

**Comment by TridentFactor** [comment]
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment 18.9 (build 11.0.4+11)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11, mixed mode)
INFO  Using log config file: jar:file:/opt/ghidra_9.0.4/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /home/ghidra/.ghidra/.ghidra-9.0.4/application.log (LoggingInitialization)  
INFO  Loading user preferences: /home/ghidra/.ghidra/.ghidra-9.0.4/preferences (Preferences)  
INFO  Class search complete (1349 ms) (ClassSearcher)  
INFO  Initializing SSL Context (SSLContextInitializer)  
INFO  Initializing Random Number Generator... (SecureRandomFactory)  
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)  
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)  
INFO  HEADLESS Script Paths:
    /home/ghidra/ghidra_scripts
    /opt/ghidra_9.0.4/Ghidra/Features/Base/ghidra_scripts
    /opt/ghidra_9.0.4/Ghidra/Features/BytePatterns/ghidra_scripts
    /opt/ghidra_9.0.4/Ghidra/Features/Decompiler/ghidra_scripts
    /opt/ghidra_9.0.4/Ghidra/Features/FileFormats/ghidra_scripts
    /opt/ghidra_9.0.4/Ghidra/Features/FunctionID/ghidra_scripts
    /opt/ghidra_9.0.4/Ghidra/Features/GnuDemangler/ghidra_scripts
    /opt/ghidra_9.0.4/Ghidra/Features/Python/ghidra_scripts
    /opt/ghidra_9.0.4/Ghidra/Features/VersionTracking/ghidra_scripts
    /opt/ghidra_9.0.4/Ghidra/Processors/8051/ghidra_scripts
    /opt/ghidra_9.0.4/Ghidra/Processors/DATA/ghidra_scripts
    /opt/ghidra_9.0.4/Ghidra/Processors/PIC/ghidra_scripts (HeadlessAnalyzer)  
INFO  HEADLESS: execution starts (HeadlessAnalyzer)  
INFO  Creating project: /opt/ghidra_projects/252ad75af5ba26cf432c10164635da0d3402e6963853052ea6a76d42180e7b69 (HeadlessAnalyzer)  
ERROR Abort due to Headless analyzer error: Unable to lock project! /opt/ghidra_projects/252ad75af5ba26cf432c10164635da0d3402e6963853052ea6a76d42180e7b69 (HeadlessAnalyzer) java.io.IOException: Unable to lock project! /opt/ghidra_projects/252ad75af5ba26cf432c10164635da0d3402e6963853052ea6a76d42180e7b69
	at ghidra.framework.project.DefaultProjectManager.createProject(DefaultProjectManager.java:106)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:425)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
	at ghidra.GhidraLauncher.main(GhidraLauncher.java:78)

**Comment by TridentFactor** [comment]
Build was successful but seems to fail on test where the Ghidra project couldn't be locked

**Comment by TridentFactor** [comment]
('sample_analysis status_code', 200)
('get_function_list status_code', 400)
get_function_list test FAILED

**Comment by OAlienO** [comment]
In this line `VOLUME /opt/ghidra_projects` ( [Dockerfile#L46](https://github.com/Cisco-Talos/Ghidraaas/blob/master/Dockerfile#L46) )
ghidra_projects has root permission
But the app only have ghidra user permission
Ghidra can't create lock file in the project folder to lock the project

**Comment by OAlienO** [comment]
If you are not intended to mount a volume

### Following is a simple fix : 

Remove `VOLUME /opt/ghidra_projects `
And Add
```
RUN mkdir -p /opt/ghidra_projects
RUN chown ghidra:ghidra /opt/ghidra_projects
```
before `USER ghidra`

**Comment by jimmy-sonny** [comment]
Thanks for reporting this issue.

I've implemented the suggested improvements.
