### ISSUE TITLE
GhIDA analysis failed 

### ISSUE THREAD

**Issue by TridentFactor** [Cisco-Talos/Ghidraaas#2]
#####Server Side 
23:05:48 DEBUG:: New xml file saved (filename: F8F97A46B5436AEA53D3324082696D16_LwMgX)
23:05:48 DEBUG:: Ghidra analysis started
[2019-09-28 23:06:18 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:568)
[2019-09-28 23:06:18 +0000] [568] [INFO] Worker exiting (pid: 568)
[2019-09-28 23:06:18 +0000] [681] [INFO] Booting worker with pid: 681

##IDA side 

GhIDA:: [DEBUG] Decompiling 403090
GhIDA:: [DEBUG] EXPORT_XML_FILE: False
GhIDA:: [!] ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
GhIDA:: [!] Decompilation error (thread)
GhIDA:: [DEBUG] Thread terminated.
GhIDA:: [DEBUG] Joining decompilation thread.
GhIDA:: [DEBUG] Thread joined. Got queue result.
GhIDA:: [!] Decompilation interrupted.

**Comment by jimmy-sonny** [comment]
The issue was related to the WORKER TIMEOUT of Gunicorn.

For more information, please refer to the gunicorn documentation:
http://docs.gunicorn.org/en/stable/settings.html#timeout

The default value is 30, changed to 300 in 5895bd7.
